name: correios_rastreio
description: Biblioteca para facilitar o rastreio de pacotes no Correio.
version: 1.0.1
repository: https://github.com/pPeterle/correios_rastreio
homepage: https://github.com/pPeterle/correios_rastreio

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4
  html: ^0.15.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
